ministryofjustice/community-api

- src/main/resources/hikari.properties
> decrease maximumPoolSize to default value of 10

- Makefile
- docker/tests/goss.yaml
Jenkins build from branch now passes: https://jenkins.engineering-dev.probation.hmpps.dsd.io/job/DAMS/job/Artefacts/job/NewTech/job/Build_Offender_Community_API/job/issue%252Fgoss_tests_failing/1/
> Increase GOSS_SLEEP value to handle increase in service start time

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/IAPSEvent.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/KeyDate.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/IAPSEventRepository.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/SpgNotificationHelperRepositoryImpl.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/service/IAPSNotificationService.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/KeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddReplaceCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_DeleteCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_GetCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/IAPSNotificationServiceTest.java
For certain changes a notification is sent to a separate system that manages interventions called IAPS (Interim Accredited Programme System). This is handled by Delius by updating a record
> DT-247 Send IAPS notification of event change

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/CreatePrisonOffenderManager.java
- src/test/java/uk/gov/justice/digital/delius/OffendersResource_AllocatePrisonOffenderManagerAPITest.java
- src/test/java/uk/gov/justice/digital/delius/OffendersResource_AllocatePrisonOffenderManagerIT.java
Add API unit tests to the allocation prison offender manager API.
> DT-400 allocate pom api tests

- src/main/java/uk/gov/justice/digital/delius/config/ApplicationInsightsConfiguration.java
- src/main/java/uk/gov/justice/digital/delius/controller/advice/SecureControllerAdvice.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/UpdateCustody.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/EventRepository.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/InstitutionalRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/CustodyController_updateCustodyTest.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/CustodyUpdateAPITest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CustodyServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- Service will be called by the `prison-to-probation-update` service when a prisoner is transferred
- at this stage this is only adding in analysis code to show what we would do on a transfer which will lead to further investigation before we implement the actual update code
> DT-463 update custody

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/OffendersResource_getOffenderByNomsNumber.java
Sorry - for the misleading commit comment 
This PR is for a new secure version of the  existing /offenders/nomsNumber/{nomsNumber}/all endpoint
> corrected formatting

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/UpdateCustodyBookingNumber.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/CustodyController_updateCustodyBookingNumberTest.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/CustodyUpdateBookingNumberAPITest.java
End point does *nothing* but needed a placeholder
> DT-466 Add do nothing end point for updating booking number

- build.gradle
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RequirementsResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ConvictionRequirements.java
- src/main/java/uk/gov/justice/digital/delius/data/api/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/AdRequirementTypeMainCategory.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/RequirementTypeMainCategory.java
- src/main/java/uk/gov/justice/digital/delius/transformers/KeyValueTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/RequirementTransformer.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/RequirementsAPITest.java
Addresses the issues raised in [this pull request](https://github.com/ministryofjustice/community-api/pull/167)
> Pic 271 add requirements endpoint review changes

- src/main/java/uk/gov/justice/digital/delius/data/api/Sentence.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Disposal.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformerTest.java
Adds termination date and reason to the convictions response
> Pic 383 add termination to order

- src/main/java/uk/gov/justice/digital/delius/service/OffenderIdentifierService.java
- src/main/java/uk/gov/justice/digital/delius/service/SpgNotificationService.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderIdentifierServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/SpgNotificationServiceTest.java
Covers the basic update scenario where there are no duplicates etc
> DT-645 NOMS number updated and SPG notified

- src/main/java/uk/gov/justice/digital/delius/data/api/UnpaidWork.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/UpwDetails.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformerTest.java
Add status - it's a standard reference field
> PIC-419 Added status to unpaid work

- .circleci/config.yml
- README.md
- docker-compose.yml
- src/main/java/uk/gov/justice/digital/delius/config/SwaggerConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AdditionalIdentifier.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferenceData.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferenceDataList.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferenceDataSets.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/ReferenceDataMaster.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/StandardReference.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ReferenceDataMasterRepository.java
- src/main/java/uk/gov/justice/digital/delius/jwt/JwtValidator.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferenceDataService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ReferenceDataTransformer.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferenceDataServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ReferenceDataTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataAPITest.java
- Endpoint to retrieve reference data for a specific data set
- Endpoint to retrieve full list of available data sets
> Dt 858 reference data additional identifiers

- src/main/java/uk/gov/justice/digital/delius/controller/advice/GeneralControllerAdvice.java
- src/main/java/uk/gov/justice/digital/delius/data/api/OffenderFilter.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getPrimaryIdentifiersTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResourceAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AuthenticationAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateBookingNumberAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateNomsNumberAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/IntegrationTestBase.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffenderIdentifiersAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_AllocatePrisonOffenderManagerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_GetAllOffenderManagersAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_GetLatestRecallAndReleaseForOffenderTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderByCrn.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderByNomsNumber.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderConvictionsByCrn.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderDocumentsByCrn.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderNsisByCrn.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getPrimaryIdentifiersAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/PersonalCircumstancesAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/RegistrationsAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/RequirementsAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/StaffResource_StaffDetailsAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/UserAPITest.java
1. Minor PR comments for typo
2. Use base integration test hence remove a ton of duplicate code
3. Minor exception login change
> DT-876 PR comments and use base test class

- src/main/java/uk/gov/justice/digital/delius/jpa/filters/OffenderFilterTransformer.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderPrimaryIdentifiers.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/OffenderPrimaryIdentifiersRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderService.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderServiceTest_getOffenderLatestRecall.java
Fix 2 issues:
1) select distinct in Oracle fails since it include all columns in OFFENDER including CLOBS
2) "APIUser" can't "see" 8 of the 2 millions offenders, so switching to "NationalUser" who should be able to see all offenders
> DT-876 Fix distinct issue by cutting down selected columns

- src/main/java/uk/gov/justice/digital/delius/data/api/OffenderAlias.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OffenderTransformerTest.java
> DT-958 Added unique key to OffenderAlias so external systems can track the entities

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/AdditionalOffence.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/CourtAppearance.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Custody.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Disposal.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Event.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/MainOffence.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Offender.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/OrderManager.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/StandardReference.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/StandardReferenceTest.java
500 error happened when 404 try to add ReferenceDate object to message
Also removed a few other circular dependencies while I was at it
> DT-994 fixed circular reference in toString causing 500 error

- src/main/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResource.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ContactRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/AttendanceService.java
- src/main/resources/db/data/V1_12__offender_add_contact_with_outcome_type_data.sql
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AttendanceServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/api/AppointmentAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResourceAPITest.java
reviewed the SQL with Alistair - we need to return all contacts with an enforcement flag (can mean a null outcome type) OR not null contact outcome type so needed an outer join.
> Pic 692 alter attendance sql

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResource.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/CourtAppearanceRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/CourtAppearanceService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtAppearanceServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesAPITest.java
New endpoint to provide court appearances for an event ID, with most recent first.
> PIC-836 add court appearances by conviction and CRN

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResource.java
- src/main/java/uk/gov/justice/digital/delius/service/CourtAppearanceService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtAppearanceServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesAPITest.java
Need 404 when the conviction is not known or not associated with the offender
> 👌🏻 PIC-836 QA issue

- README.md
- src/main/java/uk/gov/justice/digital/delius/config/AuthAwareTokenConverter.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Offender.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderManager.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/PrisonOffenderManager.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/ResponsibleOfficer.java
- src/main/java/uk/gov/justice/digital/delius/service/ContactService.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderManagerService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderManagerTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderTransformer.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderManagerTest.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderTest.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/PrisonOffenderManagerTest.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/ResponsibleOfficerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ContactService_addContactForResponsibleOfficerChangeTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderManagerService_allocatePrisonOffenderManagerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderManagerService_autoAllocatePrisonOffenderManagerAtInstitutionTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderManagerService_switchResponsibleOfficerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OffenderManagerTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OffenderTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_SwitchResponsibleOfficerTest.java
> DT-1195 Changed mapping of RO to List since it is a one to many relationship

- src/main/java/uk/gov/justice/digital/delius/config/SwaggerConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/advice/ErrorResponse.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/AuthenticationController.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CaseNoteController.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesController.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffenderDeltaControllerSecure.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffenderIdentifiersResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffenderUpdatesResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/PersonalCircumstanceResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RegistrationResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RequirementsResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/StaffResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/UserController.java
1. Added top level tags to give appropriate descriptions (and makes is alphabetical)
2. Removed 401,403 responses where they match the default
3. Removed elements in error response never used
4. Tagged APIs appropriately
> DT-1249 Improve Swagger documentation. Grouping by tags

- build.gradle
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/service/Result.java
The service that updates the prison location in Delius is about to be used in a different context. Before that could happen I needed to extract all the telemetry stuff littered in the horrible nested method. So refactored to make it more re-useable.
> DT-1318 Refactor of nested custody update to allow future reuse

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Offender.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderManagerService.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_AllocatePrisonOffenderManagerTest.java
Attempt to change the prison location when POM is allocated at a different prison.
If we are unable to change location that is fine.
TODO - telemetry for success and failure
> Dt 1318 change prison location on pom allocate

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/EventRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddReplaceCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_DeleteCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_GetCustodyKeyDateTest.java
so hat less likely to hit broken old corrupt events
> DT-1358 Limit active event service to only reading active events

- src/main/java/uk/gov/justice/digital/delius/controller/secure/TeamResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/TeamCreationResult.java
- src/main/java/uk/gov/justice/digital/delius/service/StaffService.java
- src/main/java/uk/gov/justice/digital/delius/service/TeamService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/StaffTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/StaffServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/TeamServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/TeamAPITest.java
> DT-1370 Create POM Team endpoint now also creates missing "unallocated" staff member for each team

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/LicenceCondition.java
- src/main/java/uk/gov/justice/digital/delius/transformers/KeyValueTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ContactTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/KeyValueTransformerTest.java
Also added some unit test classes, covering some pre-existing classes
> Pic 914 fix possible npe

- src/main/java/uk/gov/justice/digital/delius/controller/secure/DocumentResource.java
- src/main/java/uk/gov/justice/digital/delius/data/filters/DocumentFilter.java
- src/main/java/uk/gov/justice/digital/delius/jpa/filters/CourtReportDocumentFilterTransformer.java
- src/test/java/uk/gov/justice/digital/delius/data/filters/DocumentFilterTest.java
- src/test/java/uk/gov/justice/digital/delius/service/DocumentServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/DocumentResourceAPITest.java
To avoid confusion category is now type and type has been renamed subtype. This filter has not been released yet so not a breaking change
> DT-1377 Rename category -> type and type -> subtype

- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddReplaceCustodyKeyDateTest.java
* Add display name to each test
* Moved tests to correct Nested class for clarity
> DT-1439 Refactor tests prior to functional change

- src/test/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesControllerTest.java
> DT-1440 Fix date test

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
Will remove the endpoint after court case service has migrated forward
> PIC-674 Add path ending "custodialStatus" to allow compatibility 

- src/main/java/uk/gov/justice/digital/delius/config/SwaggerConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RegistrationResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RiskResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/MappaDetails.java
- src/main/java/uk/gov/justice/digital/delius/service/RiskService.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/RiskAPITest.java
I have just defined the API for now, implementation to follow.
> DT-1542 Surface offender MAPPA details

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/CourtAppearanceMinimal.java
- src/main/java/uk/gov/justice/digital/delius/data/api/CourtAppearanceMinimalWrapper.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/CourtAppearance.java
- src/main/java/uk/gov/justice/digital/delius/service/CourtAppearanceService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceBasicTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceMinimalTransformer.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesAPITest.java
Streamline slow court appearance endpoint
> Pathfinder national extract times out

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderService.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderServiceTest_getOffenderLatestRecall.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/IntegrationTestBase.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_updateTier.java
hmpps-tier will write the recalculated tier back into delius via community-api
A new role has been created for this new endpoint, but it's just a string in this project at the moment. What else has to happen to allow it to be used?
> MAS-283 update offender tier

- src/main/java/uk/gov/justice/digital/delius/service/TierService.java
- src/test/java/uk/gov/justice/digital/delius/service/TierServiceTest.java
There isn't an integration test for this work because SpgNotificationHelperNoProceduresRepositoryImpl which is present in the profile used by the tests never returns any interested CRCs, hence no notifications will be created
> MAS-323 create an SPG Notification

- src/main/java/uk/gov/justice/digital/delius/service/TierService.java
- src/test/java/uk/gov/justice/digital/delius/service/TierServiceTest.java
The reference data exists in all environments now following the deployment of the weekend's delius release PDM 21.10
> MAS-341 remove fallback for absence of tiering reference data

- src/main/java/uk/gov/justice/digital/delius/data/api/RiskResourcingDetails.java
> DT-1570 Fix Swagger description

- src/main/resources/application.yml
Correction to configuration for mapping attended/behaviour data to outcomes. Yes/No get translated to true and false by spring. Need to be quoted.
Correction.
**Breaking Changes?**
None
> DAPI-171 Correction to configuration

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtResource.java
- src/main/java/uk/gov/justice/digital/delius/service/CourtService.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CourtAPITest.java
1. Use `Either` pattern rather then exception
2. Endpoint to get all courts
> DT-1780 Get all courts and improve update errors

- .gitignore
- src/main/java/uk/gov/justice/digital/delius/controller/secure/TeamResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/OfficeLocation.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Team.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/TeamRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/TeamService.java
- src/main/resources/application-dev-file.yml
- src/test/java/uk/gov/justice/digital/delius/controller/secure/TeamResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/TeamServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/TeamAPITest.java
> e2e-484 get team office locations

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtResource.java
- src/main/java/uk/gov/justice/digital/delius/service/CourtService.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CourtAPITest.java
* Changed reference data lookup errors to 400 error (was 500) as convention 
* Changed url to plural `courts` from `court` as convention
> Dt 1780 testing issues

- src/main/resources/application.yml
- src/testIntegration/resources/application.properties
Configuration to cover additional Contract Type or NSI Type mappings.
Support for additional Contract Types in Delius.
**Breaking Changes**
None
> DAPI-164 Mapping additional Contract Types to Delius Nsi Types via config

- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentCreateResponse.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/wiremock/DeliusApiMockServer.java
Added sensitive flag to create appointment api. This is just passed through to delius api.
> E2E-487 sensitive appointment

- build.gradle
- DT-2070: ⬆️ Upgrade to spring boot 2.5.0 and kotlin 1.5.10
- DT-2070: ⬆️ Upgrade to 3.3.0 of gradle plugin
> pgp DT 2070 spring boot upgrade

- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_GetProbationStatusTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
Scenario:
Court Appearance with no outcome
Court Appearance with outcome other the PSR
Result NPE
This PR filter out Appearances with no outcome
> DT-2606 Fix NPE for court appearance with no outcome

- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
Fix appointments on same day not sorted by time
> E2E-547: sort appointments by date & time

- src/main/java/uk/gov/justice/digital/delius/config/DeliusIntegrationContextConfig.java
- src/main/java/uk/gov/justice/digital/delius/transformers/NsiPatchRequestTransformer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/transformers/NsiPatchRequestTransformerTest.java
- src/testIntegration/resources/application.properties
On Referral End change NSI Status to completed (from in-progress) and update status time
Ensure all necessary fields are kept in sync in delius
**Breaking Changes?**
None
> DAPI-187 On Referral End set NSI Status to COMP and update status time

- src/main/java/uk/gov/justice/digital/delius/data/api/Conviction.java
- src/main/java/uk/gov/justice/digital/delius/data/api/Court.java
- src/main/java/uk/gov/justice/digital/delius/data/api/CourtAppearanceBasic.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/CourtAppearance.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceBasicTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceBasicTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderConvictionsByCrn.java
Adds new fields to the sentence dto.
* responsible court: mapped through from event.court (this is actually named responsibleCourt in delius)
* courtAppearance: latest sentence appearance or latest appearance otherwise. Logic taken from delius.
> E2E-555: added court & responsible court to conviction dto

- .circleci/config.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Reverts ministryofjustice/community-api#494
> Revert "DT-2253: ⬆️ Upgrade spring boot / kotlin"

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/PersonalContact.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Offender.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/PersonalContact.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/PersonalContactTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/DocumentTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/PersonalContactTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_PersonalContactsTest.java
> E2E-606: get offender personal contacts api

- src/main/java/uk/gov/justice/digital/delius/data/api/PersonalCircumstance.java
- src/main/java/uk/gov/justice/digital/delius/transformers/PersonalCircumstanceTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/PersonalCircumstanceTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
Last updated & created dates returned on offender personal circumstance api.
> E2E-629: expose personal circumstances modified dates

- src/main/java/uk/gov/justice/digital/delius/data/api/AddressSummary.java
- src/main/java/uk/gov/justice/digital/delius/data/api/PersonalContact.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Address.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/PersonalContact.java
- src/main/java/uk/gov/justice/digital/delius/transformers/PersonalContactTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/PersonalContactTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_PersonalContactsTest.java
expose personal contact address
> E2E-630: personal contact address

- src/main/java/uk/gov/justice/digital/delius/controller/secure/AppointmentControllerSecure.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentDetail.java
- src/main/java/uk/gov/justice/digital/delius/jpa/filters/AppointmentFilter.java
- src/main/java/uk/gov/justice/digital/delius/jpa/filters/ContactFilter.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Contact.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/ContactType.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ContactRepository.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ContactTypeRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/NotificationService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ContactTransformer.java
- src/main/resources/db/data/V1_12__offender_add_contact_with_outcome_type_data.sql
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentControllerSecureTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/NotificationServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ContactTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentAPITest.java
> E2e 634 get appointment

- .project
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ContactMetaController.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/ContactType.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ContactTypeRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/ContactService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ContactTransformer.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/ContactMetaControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ContactService_getContactTypesTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ContactMetaControllerApiTest.java
Added new endpoint to get contact types by categories.
> New contact types endpoint

- src/main/java/uk/gov/justice/digital/delius/data/api/ContactSummary.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Contact.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ContactTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ContactTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ContactApiTest.java
**Reason for the change -** 
Added details of last contact update, required for communication details page.
https://trello.com/c/wp1AzwLO/633-build-the-communication-details-page
**Breaking change?**
No
> Trello - 633-build-the-communication-details-page

- src/main/java/uk/gov/justice/digital/delius/data/api/ActivityLogGroup.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContactRarActivity.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContactSummary.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ContactTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ContactTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ContactApiTest.java
Get RAR activity meta on the contact summary APIs
> E2E-830: Added RAR activity detail to the contact summary APIs

- .gitignore
- .trivyignore
> Updated .trivyignore and removed reference from .gitignore

- src/main/resources/application.yml
Adds the new contract type NSI mappings for the new contracts going live 3rd October.
> add new contract type mappings

- src/main/resources/application.yml
New nsi mappings for the contracts going live 10th October
> add contract-type nsi mappings

- src/main/resources/application.yml
Contract to NSI mapping for FBD North west
> contract to nsi mapping for FBD-NW

- src/main/java/uk/gov/justice/digital/delius/controller/secure/AttendanceResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtAppearancesResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CourtReportResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/DocumentResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RegistrationResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RequirementsResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RiskResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/StaffResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/TeamResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/UserController.java
This is the same approach we use for probation integration services.
> Allow probation-integration admins to call Community API

- helm_deploy/values-test.yaml
to match Delius database schedule
> PI-2965 Set timezone for scheduled downtime job

- helm_deploy/community-api/Chart.yaml
As we're still getting errors between 9pm-10pm.
> Upgrade Helm chart version to include time zone config
