- src/main/java/uk/gov/justice/digital/delius/controller/LogonController.java
- src/test/java/uk/gov/justice/digital/delius/LogonAPITest.java
Delius has a special system user for doing updates `APIUser`. This used for things like Case Notes Poll pusher. 
Therefore require special code to allow systems to "login" for that user that exists in database but not LDAP. So we treat APIUser like we do NationalUser.
> DT-247 Allow logon of special "APIUser" for system-system calls

- src/main/resources/logback-spring.xml
To allow app insights and console logging in a prod "oracle" profile. This is different to other DPS apps since this API is shared with probation that don't yet app insights yet.
> DT-341 Allow console and app insights logging at same time

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderService.java
- src/test/java/uk/gov/justice/digital/delius/OffendersResource_GetLatestRecallAndReleaseForOffender.java
Add the crn version of the recall/release endpoint, and check for offender not found.
Lacking any consumers and returning no data, this can be safely merged into master once approved.
> DT-337 recall by crn

- src/test/java/uk/gov/justice/digital/delius/OffendersResource_AllocatePrisonOffenderManagerAPITest.java
- src/test/java/uk/gov/justice/digital/delius/OffendersResource_AllocatePrisonOffenderManagerIT.java
I initially thought these tests could be refactored by mocking the service but they are actually testing logic in the service - so I've moved them back into the integration test class.
> DT-400 Move the allocate POM integration tests to their rightful home

- src/main/java/uk/gov/justice/digital/delius/data/api/Team.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Borough.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/ProbationArea.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferenceDataService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/TeamTransformer.java
- src/test/java/uk/gov/justice/digital/delius/ReferenceDataResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferenceDataServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/TeamTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
This is because local_delivery_unit really refers to team type.
This effects 4 endpoints:
* /allOffenderManagers
* /staff/code
* /staff/username
* /probationArea/localdeliveryunits
Which were all added recently for licences.
> DCS-312 Exposing district as LDU rather than local_delivery_unit

- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferenceDataResource.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferenceDataService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/TypesTransformer.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/ReferenceDataResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferenceDataServiceTest.java
So now:
* Only including selectable LDUs from new endpoints
* Also now returning all teams for a given LDU code rather than just those for the first LDU with that specific code
> DCS-329 Fixing returned data from new reference data endpoints

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderPrisoner.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/OffenderPrisonerPk.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/OffenderPrisonerRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/ContactService.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderPrisonerService.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/CustodyUpdateBookingNumberAPITest.java
- src/test/java/uk/gov/justice/digital/delius/service/ContactService_addContactForBookingNumberUpdateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CustodyServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderPrisonerServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
We replicate Delius when updating booking number which includes
- Updating the booking number (aka prison number) on Custody record
- Updating the most recent number of the Offender record
- Recreating all the associated OFFENDER_PRISONER records
- Creating a CONTACT record
- Notify CRCs via the SPG of the updated EVENT
All rules have been lifted from existing Delius legacy application
> Do the Delius Updates

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/EventRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/OffendersResource_getOffenderConvictionsByCrn.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
Code returns the same conviction type but just for a single ID.
Search by event ID which is PK on the EVENT table.
> Add an endpoint to retrieve the details of a single conviction

- src/main/java/uk/gov/justice/digital/delius/service/NsiService.java
- src/test/java/uk/gov/justice/digital/delius/integration/secure/OffendersResource_getOffenderNsisByCrn.java
- src/test/java/uk/gov/justice/digital/delius/service/NsiServiceTest.java
Was returning 404 for a conviction ID which did exist for an offender in the events table but which had no entries in the NSI table. Wanted an empty list in this case.
> pic 381 - 404 if conviction ID doesn't 

- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddOrReplaceOrDeleteCustodyKeyDatesTest.java
For reasons unknown Delius doe not write a IAPS (?)  row when a sentence expiry date is removed via the DSS feature. This replicates the same behaviour.
> DT-784 Fix to not notify IAPS when SED changes due to DSS

- .circleci/config.yml
- build.gradle
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateBookingNumberAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyUpdateNomsNumberAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffenderIdentifiersAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_AllocatePrisonOffenderManagerIT.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/PersonalCircumstancesAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/RegistrationsAPITest.java
Tactical solution to get all tests running with running out of memory; run them in 4 parallel containers.
- Strategic solution is to convert some SpringBoot tests to our unit tests
- Remove the need to reload flyway data using test transactions
> Dt 835 parallel circle steps

- src/main/java/uk/gov/justice/digital/delius/entitybuilders/AdditionalOffenceEntityBuilder.java
- src/main/java/uk/gov/justice/digital/delius/entitybuilders/CourtAppearanceEntityBuilder.java
- src/main/java/uk/gov/justice/digital/delius/entitybuilders/EventEntityBuilder.java
- src/main/java/uk/gov/justice/digital/delius/entitybuilders/KeyDateEntityBuilder.java
- src/main/java/uk/gov/justice/digital/delius/entitybuilders/MainOffenceEntityBuilder.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CustodyKeyDateTransformer.java
- src/test/java/uk/gov/justice/digital/delius/entitybuilders/AdditionalOffenceEntityBuilderTest.java
- src/test/java/uk/gov/justice/digital/delius/entitybuilders/CourtAppearanceEntityBuilderTest.java
- src/test/java/uk/gov/justice/digital/delius/entitybuilders/EventEntityBuilderTest.java
- src/test/java/uk/gov/justice/digital/delius/entitybuilders/MainOffenceEntityBuilderTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddOrReplaceOrDeleteCustodyKeyDatesTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddReplaceCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_DeleteCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_GetCustodyKeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtAppearanceServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CourtReportServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/DocumentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/InstitutionalReportServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenceServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/PersonalCircumstanceServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/RegistrationServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/UserServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/CustodyKeyDateTransformerTest.java
Final part of transformer refactoring
1. Split a few more transformers between transforming a model object from an entity to the opposite, building a entity
2. Renamed (and moved) the class that build entities to <Name>EntityBuilder after realising these don't transform, they build
3 Any service test that previously needed the Spring Runner to inject the mess of transformers are now pure mocked tests
4 With two tests left that might benefit from using SpringRunner decided to make them consistent, and just use the `MockitoExtension`
> DT-864 Convert Spring tests to pure unit tests and split out entity builders

- src/main/java/uk/gov/justice/digital/delius/service/UserService.java
- src/test/java/uk/gov/justice/digital/delius/service/UserServiceTest.java
hmpps auth will require the username in the email search response in order to inform clients of the user's delius username
> add username field to /users/search and /users/{username}/detail responses

- build.gradle
- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesController.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/IntegrationTestBase.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_AllocatePrisonOffenderManagerTest.java
1. Endpoints that update POMs and Key Dates new require the ROLE_COMMUNITY_CUSTODY_UPDATE role
2. OWASP fix
> DT-1099 Update keydates and POM now require update role

- src/main/java/uk/gov/justice/digital/delius/controller/secure/StaffResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ManagedOffender.java
- src/main/java/uk/gov/justice/digital/delius/data/api/StaffDetails.java
- src/main/java/uk/gov/justice/digital/delius/service/StaffService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/StaffTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/StaffServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OffenderTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/StaffTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/StaffResource_ManagedOffendersAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/StaffResource_StaffDetailsAPITest.java
New secure endpoints for retrieving staff details and managed offenders by staff identifier (staff id)
```
GET /secure/staff/staffIdentifier/{staffIdentifier}
GET /secure/staff/staffIdentifier/{staffIdentifier}/managedOffenders
```
Also added staffIdentifier property to `...api.StaffDetails` and `...api.ManagedOffender`
Happy to change `staffIdentifier` to `staffId` if the abbreviation is preferred...
> DCS-607 New end-points for retrieving staff details and managed offenders by staffIdentifier

- src/main/java/uk/gov/justice/digital/delius/config/ClientTrackingTelemetryModule.java
- src/main/java/uk/gov/justice/digital/delius/controller/advice/GeneralControllerAdvice.java
Suppress exception under these categories that is polluting logs:
1. AWS `health/ping` is sending a bearer token that we don't care about
2. case notes correctly return 404 - but we don't need an exception in the logs for that
> DT-1195 Get rid of confusing exceptions in log

- src/main/java/uk/gov/justice/digital/delius/data/api/Nsi.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Nsi.java
- src/main/java/uk/gov/justice/digital/delius/transformers/NsiTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/NsiTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderNsisByCrn.java
Unlike the other dates in this object (start, referral, actual start), there is a time component stored in the database. Don't want to throw away - consumers can disregard if they wish
> ✨ PIC-830 add status date to NSI response

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/SmokeTestHelperResource.java
- src/main/java/uk/gov/justice/digital/delius/data/api/Custody.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/InstitutionRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/service/SmokeTestHelperService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/service/CustodyServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/CustodyGetAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/SmokeTestHelperAPITest.java
- src/testIntegration/resources/application.properties
The purpose of this PR is to provide and endpoint that would allow a test client to "reset" custody data as if the prison-to-probation-update had never been called. This involves
- removing the NOMS number and book number
- setting the prison location back to unknown
- setting the custodial status back to "Sentenced"
- removing the key dates
To also help a test client new endpoints have been added (which are generally useful) which can help to assert that data has been successful reset and set for a successful test
> Dt 1271 smoke test data rest

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/StaffRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/StaffService.java
- src/test/java/uk/gov/justice/digital/delius/service/StaffServiceTest.java
Problem:
When MOiC assigns a POM a new Staff member is created with same name as the POM. This Staff member is reused when a POM is assigned to a new prisoner.
This was error if more than one Staff member was found with the same name (JPA error).
This change chooses the first one, since MOiC only cares that the correct name is assigned, the Staff entity has no meaning other than the name.
> DT-1308 Allow for multiple Staff in a prison with the same name. 

- src/main/java/uk/gov/justice/digital/delius/data/api/Human.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/StaffRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderManagerService.java
- src/main/java/uk/gov/justice/digital/delius/service/StaffService.java
- src/main/resources/db/schema/V1_0__schema.sql
- src/test/java/uk/gov/justice/digital/delius/data/api/HumanTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderManagerService_allocatePrisonOffenderManagerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/StaffServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_AllocatePrisonOffenderManagerTest.java
OMiC will supply POM names in upper case; e.g JOHN SMITH
This resolves two issues:
1) When Staff already exists regardless of case - use that existing staff, so JOHN SMITH will match an existing john smith
2) When creating a new staff member capitalise - e.g transform to John Smith
> DT-1334 Capitalise POMs names and find existing Staff regardless of case

- src/main/java/uk/gov/justice/digital/delius/data/api/Custody.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/service/CustodyService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/test/java/uk/gov/justice/digital/delius/entitybuilders/EventEntityBuilderTest.java
- src/test/java/uk/gov/justice/digital/delius/service/CustodyServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
Previous if an offender had multiple sentences (events) we would not update the prison location on any of the events but return an error, this change will updated each active custodial event (based on current rules around custodial status)
> Dt 1439 prison location multiple custodial events

- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionService_AddReplaceCustodyKeyDateTest.java
Previously if multiple custodial events where found we would update none, now we update all, changes requested by PAS
> DT-1440 Single Key dates updated / added on all active custodial events

- src/main/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesController.java
- src/main/java/uk/gov/justice/digital/delius/data/api/Custody.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/CustodyKeyDatesControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
Previously for NOMIS date changes we would update no dates if there were multiple active custodial events; this reverses this decision to update dates for all events associated with the prison the booking, therefore indicating all sentences active are affected by the date change
> DT-1440 Update all matching custodial events that have book number

- src/main/java/uk/gov/justice/digital/delius/config/AuthAwareTokenConverter.java
- src/testIntegration/java/uk/gov/justice/digital/delius/config/AuthAwareTokenConverterTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/IntegrationTestBase.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderByCrn.java
Fixes a bug where the JWT scopes were not being copied into authorities and so didn't work.
> DT-1613 extract jwt scopes

- .circleci/config.yml
Uses the [aws-ecs](https://circleci.com/developer/orbs/orb/circleci/aws-ecs) orb, with AWS credentials stored in CircleCI contexts, to enable deployment to the various Delius environments.
This enables automatic deployment to the `delius-core-dev` environment on every git push, to enable better feedback against pull requests. This may be contentious so feel free to remove it if it's a problem.
> ALS-2724 Enabled deployments to ECS

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/RegistrationResource.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/RegistrationsResourceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderServiceTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderConvictionsByNoms.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/RegistrationsAPITest.java
This brings
/offender/nomsNumber/:nomsNumber/registrations
/offender/nomsNumber/:nomsNumber/convictions
in line with 
/offender/nomsNumber/:nomsNumber
/offender/nomsNumber/:nomsNumber/all
It assumes if there are duplicate records for the same NOMS number it will return the active one else error will be 409 rather than 500 error.
Old behaviour can be restored using additional parameter (though unlikely anybody would want the old behaviour)
> Dt 1801 500 errors registrations

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/service/OffenderManagerService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderManagerTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/OffenderManagerService_getAllOffenderManagersTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OffenderManagerTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_GetAllOffenderManagersAPITest.java
Flag defaults to false. Observation on this and other similar endpoints is that the inclusion of all teams on probation areas can massively increase the size of the JSON. Consumers of these endpoints do not use them.
> ✨ PIC-1288 flag to include teams in the ProbationAreas 

- src/main/java/uk/gov/justice/digital/delius/config/DeliusIntegrationContextConfig.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferralSentRequest.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/utils/DateConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/ReferralControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/utils/DateConverterTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferralAPITest.java
- src/testIntegration/resources/application.properties
After completing the end to end integration between Interventions and Delius UI (via community-api and delius-api) a number of improvements were identified in order to have a working integration. These comprise:
- Interventions to provide offsets with dates and times so that appointments and referrals can be converted correctly for Delius which relies on Europe/London local dates and times
- Use UUIDs over long text to identify reference data (e.g. service category). The use of descriptions was deemed fragile ( business codes are not available for service categories)
- Provide integration context in all requests to identify the correct mapping configuration for a client of community-api
To achieve a workable …
> DAPI-88 Interventions Capi Integration Improvements

- build.gradle
- src/main/java/uk/gov/justice/digital/delius/config/DeliusIntegrationContextConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingController.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentUpdateResponse.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessAppointmentOutcomeRequest.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/DeliusApiClient.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformer.java
- src/main/java/uk/gov/justice/digital/delius/utils/JsonPatchSupport.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/utils/JsonPatchSupportTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/wiremock/DeliusApiMockServer.java
- src/testIntegration/resources/application.properties
Introduced a new endpoint to carry out an appointment with an outcome type - for a specified context, e.g. commissioned rehabilitation services. Context specific PATCH hasn't been used after further technical and requirements discussions.
@RequestMapping(value = "/offenders/crn/{crn}/appointments/{appointmentId}/outcome/context/{contextName}",
method = RequestMethod.POST, consumes = "application/json")
To make the update compatible with Delius the following transformation is done:
1) attended (Yes/No/Late) and notifyPPOfAttendanceBehaviour (true/false) are mapped to a single replace operation on outcome (e.g. AFTC)
This enables consumers of community-api to update Delius with the outcome of an appointment. …
> DAPI-171 Update of Appointment with Outcome for Context of CRS

- src/main/java/uk/gov/justice/digital/delius/config/DeliusIntegrationContextConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingController.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferralController.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessReferralStartRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferralStartResponse.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/service/RequirementService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/controller/secure/ReferralControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/RequirementServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferralAPITest.java
- src/testIntegration/resources/application.properties
After a review of the interaction with Interventions, a number of changes where identified for the referral sent end point:
1) A more generic name for the endpoint is ReferralStart
2) Referrals are not limited to Sentences with RAR requirements, and thus, exception not raised if requirement not found
2) ContractType is to be used to map to NsiType instead of ServiceCategory
3) SentAt is renamed to StartedAt
4) Context name is to be specified in URL as apposed to in the body - in line with appointment creation
This change means that the initial release of interventions can be supported.
**Breaking Changes?**
Yes and limited to interventions referralSent endpoint.
> DAPI-172 DAPI-173 Changes to Referral Start endpoint for interventions

- src/main/java/uk/gov/justice/digital/delius/config/DeliusIntegrationContextConfig.java
- src/main/java/uk/gov/justice/digital/delius/controller/secure/ReferralController.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessReferralEndRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ReferralEndResponse.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/ContactRepository.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/DeliusApiClient.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/NsiPatchRequestTransformer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/justice/digital/delius/controller/secure/ReferralControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/NsiPatchRequestTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferralAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/wiremock/DeliusApiMockServer.java
- src/testIntegration/resources/application.properties
Referrals in Interventions can end in one of three ways. They can be cancelled, prematurely ended or completed in their entirety. As a result, delius must be updated with the appropriate outcome and where there are any outstanding appointments, they must be deleted from delius. This PR provides this functionality.
These changes allow interventions to end referrals with the knowledge that delius has been kept up to date.
**Breaking Changes?**
None
> DAPI-99 Referral End request

- src/main/java/uk/gov/justice/digital/delius/controller/secure/AppointmentControllerSecure.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentDetail.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentOutcome.java
- src/main/java/uk/gov/justice/digital/delius/data/api/KeyValue.java
- src/main/java/uk/gov/justice/digital/delius/data/api/StaffHuman.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Contact.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/TeamService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OfficeLocationTransformer.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentControllerSecureTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentAPITest.java
New API for getting offender appointments by CRN. Uses same URL structure as existing, /api endpoint.
> E2E-520: Get offender appointments

- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessAppointmentCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessNotificationCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessReferralEndRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessReferralStartRequest.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/service/NotificationService.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ReferralTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/NotificationServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ReferralTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/ReferralAPITest.java
There is an edge case when more that one Referral may be created in R&M that appear to cover the same Intervention, i.e. are for the same CRN and Sentence, cover the same Contract Type (e.g. Personal Wellbeing) and start on the same date. Prior to this change they would both be tied to the same NSI in Delius. After this change, each one results in its own NSI using the ReferralId (in the form of an URN) to distinguish them ... should an initial search return multiple. The belief is this case is rare and so the additional filtering by URN will not come into play most of the time. There is no designated field for the URN to reside in so it is held in the Notes as an initial entry. The Notes field is never replaced, only appended too.
Specifically the …
> DAPI-177 When searching for a matching NSI using existing criteria, if multiple are found, then use ReferralId (URN) to find a unique one. 

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_checkUserAccessByCrn.java
this change has two parts
1. change the permissions on the existing `/offenders/crn/{crn}/userAccess` endpoint to allow it to be called with delius user tokens (ROLE_PROBATION).
2. add a new endpoint which allows specifying the username in the url to allow regular client credentials granted tokens the ability to use the endpoint without requesting a new 'username' scoped token.
> Update 'user access' endpoints to be more flexible 

- src/main/java/uk/gov/justice/digital/delius/data/api/Nsi.java
- src/test/java/uk/gov/justice/digital/delius/data/api/NsiTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderNsisByCrn.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getRecallNsisForOffenderByNomsNumberAndActiveConvictions.java
* Added isOutcomeRecall and isRecallRejectedOrWithdrawn on Nsi API 
* Only present when NSI is a recall
Added so that clients have a quick view of the recall without having to understand the meaning of Delius ref data codes
> DT-2606 Add attributes on Nsi when recall to indicate outcome and status

- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformerTest.java
Always set RAR Activity Flag when contact is linked to a RAR Requirement, even when it doesn't count towards RAR days (i.e. false), regardless of whether the contact has a type that is defined as "RAR Activity No".
Correction to the logic otherwise Delius-Api rejects the contact.
None
> IC-1722 Always set RAR Activity Flag when contact is linked to a RAR Requirement

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Custody.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/KeyDate.java
- src/main/java/uk/gov/justice/digital/delius/service/NsiService.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/CustodyTest.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/KeyDateTest.java
- src/test/java/uk/gov/justice/digital/delius/service/NsiServiceTest.java
This specialised endpoint has intent of returning RECALL requests that maybe "active", e.g an outstanding request or released to a current custodial sentence.
If a licence period is past then this is a historic NSI and is no longer of interest.
> DT-2054 Exclude recall NSIs with an expired licence

- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/service/RequirementService.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/RequirementServiceTest.java
Community Api should exclude inactive requirements when deriving the RAR requirement for a CRN sentence during the process of initiating a NSI in Delius. Also, any post request made for an NSI that has duplicates in Delius should result in a 400. The NSIs must be cleaned up in Delius before they can be acted upon.
Fix issues arising in production
**Breaking Changes**
None.
> IC-2016 Referral Send must exclude inactive RAR requirements

- src/main/java/uk/gov/justice/digital/delius/data/api/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/service/RequirementService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/RequirementTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/RequirementServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/RequirementTransformerTest.java
**What is included in this change?**
The creation of a NSI and the association of a referral was implemented on the basis that there is only ever one active requirement per service user sentence. This is not always the case. It has been agreed that should multiple exist, the one with the latest start date should be chosen and associated to the NSI. Where start date is the same, the later create date time is used.
This is to resolve a matter arising in production with approximately 1% of referrals raised by R&M.
**Are there any breaking changes?**
None, but introduced createDateTime in api class Requirement.
> IC-2050 When creating an NSI and in the case of multiple RAR requirements, take the latest

- src/main/java/uk/gov/justice/digital/delius/data/api/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/service/RequirementService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/RequirementTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/RequirementServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/RequirementTransformerTest.java
What is included in this change?
During the referral start/NSI creation request, a requirement is selected from the specified sentence. Soft deleted requirements must be excluded from the selection.
What is the intent behind these changes?
This is to resolve a matter arising in production by R&M.
Are there any breaking changes?
None, but introduced attribute softDeleted in api class Requirement.
> IC-2067 Exclude soft deleted RARs during NSI Creation/Referral Sent process

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Custody.java
- src/test/java/uk/gov/justice/digital/delius/jpa/standard/entity/CustodyTest.java
Endpoint does not return recall NSIs after the licence period, however in live it was observed that some Events had no licence expiry date but had entered the PPS phase (so therefore had passed licence expiry) - e.g LED was just not present in Delius but obviously does exists in real world.
So if sentence has entered PSS no need to consult LED since by definition licence period has expired.
> DT-2054 Exclude recall NSIs which is in PSS phase

- src/main/java/uk/gov/justice/digital/delius/data/api/Conviction.java
- src/main/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceBasicTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/ConvictionTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/CourtAppearanceBasicTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderConvictionsByCrn.java
Adds a flag to the Conviction to indicate whether or not that conviction is awaiting a PSR.  It looks amongst the outcomes on the appearances, which are already fetched as part of another field.
> ✨ PIC-1527 add awaiting PSR to conviction

- src/main/java/uk/gov/justice/digital/delius/data/api/OffenderDetailSummary.java
- src/main/java/uk/gov/justice/digital/delius/transformers/OffenderTransformer.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getOffenderByCrn.java
Preferred name was added to the offender detail api but not the offender summary api
> E2E-634: fix offender summary not returning preferred name

- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentDetail.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Requirement.java
- src/main/java/uk/gov/justice/digital/delius/service/ConvictionService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/RequirementTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/ConvictionServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/service/RequirementServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/NsiTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/RequirementTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
Appointment consumers are interested in whether or not an appointment relates to a RAR requirement. This compliments the RAR_ACTIVITY flag for determining whether the appoint had anything to do with RAR. Decided not to include the entire requirement in the response for performance.
> E2E-634: expose rar requirement id on appointment apis

- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentRescheduleRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessAppointmentRescheduleRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/deliusapi/ReplaceContact.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
**What is included in this change?**
This change allows an office location to be provided as part of an appointment rescheduling. If not supplied it remains unchanged. 
What is the intent behind these changes?
Provide R&M the functionality it needs.
**Are there any breaking changes?**
No, but introduced an optional office location field to the reschedule request dto's
> IC-2028 Include Office Location as part of Appointment Reschedule

- src/main/java/uk/gov/justice/digital/delius/data/api/Nsi.java
- src/main/java/uk/gov/justice/digital/delius/service/ReferralService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/NsiTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/ReferralServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/NsiTransformerTest.java
As part of the integration with R&M, when finding a matching NSI Community-api must exclude "soft-deleted" NSI's.
This is to fix a rare situation after which duplicate NSIs are present in nDelius, which then need to be manually deleted from nDelius.
**Any breaking changes?**
None
> IC-2141 Exclude "soft-deleted" nsi's

- src/main/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingController.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentRelocateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentRelocateResponse.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformer.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingControllerTest.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformerTest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/secure/AppointmentBookingAPITest.java
- src/testIntegration/java/uk/gov/justice/digital/delius/controller/wiremock/DeliusApiMockServer.java
Added a new community-api endpoint for relocation of an existing appointment where location is the only thing that has changed.
To avoid using the reschedule endpoint. The endpoint makes the original rescheduled time slot unavailable for any new appointments which would means a second change of location not possible even when the times remain the same.
**Any breaking changes?**
None
> IC-2165 New endpoint for only changing the location of an appointment

- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Event.java
- src/main/java/uk/gov/justice/digital/delius/jpa/standard/entity/Requirement.java
Fixed a couple of these warnings:
warning: @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
> fix default value lombok build warnings

- src/main/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource.java
- src/test/java/uk/gov/justice/digital/delius/controller/secure/OffendersResource_getActivityLogByCrnTest.java
Fix:
```
java.lang.NullPointerException: Cannot invoke "uk.gov.justice.digital.delius.data.api.Sentence.getTerminationDate()" because the return value of "uk.gov.justice.digital.delius.data.api.Conviction.getSentence()" is null
at uk.gov.justice.digital.delius.controller.secure.OffendersResource.lambda$getActivityLogByCrn$15(OffendersResource.java:331)
```
> E2E-794: fix null pointer exception when sentence is null

- src/main/java/uk/gov/justice/digital/delius/data/api/AppointmentCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/ContextlessAppointmentCreateRequest.java
- src/main/java/uk/gov/justice/digital/delius/data/api/deliusapi/NewContact.java
- src/main/java/uk/gov/justice/digital/delius/service/AppointmentService.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformer.java
- src/main/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/AppointmentServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentCreateRequestTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/AppointmentPatchRequestTransformerTest.java
https://trello.com/c/HnxgCLKB/137-create-appointment-with-a-date-in-the-past
This feature allows the creation of an appointment in the past. Outcome and enforcement values can now be provided for historic appointments which is required by delius-api. 
R&M users have been unable to create appointments retrospectively which is part of the practise they follow. This now facilitates that process.
**Any breaking changes?**
There are no breaking changes.
AppointmentCreateRequest body now contains optional fields for outcome and enforcement, e.g. "AFTC and ROM". These are now also included in requests to delius-api.
> Trello-137 Creation of an appointment in the past by providing an outcome and enforcement values

- src/main/java/uk/gov/justice/digital/delius/data/api/PersonalCircumstance.java
- src/main/java/uk/gov/justice/digital/delius/transformers/PersonalCircumstanceTransformer.java
- src/test/java/uk/gov/justice/digital/delius/service/PersonalCircumstanceServiceTest.java
- src/test/java/uk/gov/justice/digital/delius/transformers/PersonalCircumstanceTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
https://dsdmoj.atlassian.net/browse/ARN-770
This PR adds an activeFlag property to the PersonalCircumstance DTO. The active flag is determined in the PersonalCircumstanceTransformer as true if the start date is before or is today and the end date is after today or null, otherwise the active flag is false.
The Assess Risks and Needs service requires the activeFlag field to use with the existing jsonPath to filter only the currently active PersonalCircumstances for use in Unpaid Work assessments. 
**Any breaking changes?**
There are no breaking API changes.
> Arn 770 add active flag to personal circumstance

- src/main/java/uk/gov/justice/digital/delius/service/StaffService.java
- src/test/java/uk/gov/justice/digital/delius/service/StaffServiceTest.java
* Telephone number exists on the staff details by username endpoint, but is missing from the staff details by staffId endpoint
* This PR adds it by re-using the `addFieldsFromLdap` private function
> Add telephone number from LDAP to staff details endpoint

- src/main/java/uk/gov/justice/digital/delius/transformers/OrderManagerTransformer.java
- src/test/java/uk/gov/justice/digital/delius/transformers/OrderManagerTransformerTest.java
- src/test/java/uk/gov/justice/digital/delius/util/EntityHelper.java
This is a rare occurrence, however there are 42 old records in production where the ALLOCATION_STAFF_ID / ALLOCATION_TEAM_ID columns are null. Hopefully the data can be corrected by NDST, but this change ensures we'll safely handle any null values in the meantime.
> PI-101 Handle null staff/team on OrderManager

- .circleci/config.yml
- build.gradle
This release will
* Upgrade to spring-boot 2.6.4
* org.owasp.dependencycheck [6.5.3 -> 7.0.0]
* com.github.ben-manes:gradle-versions-plugin [0.41.0 -> 0.42.0]
* com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin [0.41.0 -> 0.42.0]
* com.google.code.gson:gson [2.8.9 -> 2.9.0]
* com.gorylenko.gradle-git-properties:com.gorylenko.gradle-git-properties.gradle.plugin [2.3.2 -> 2.4.0]
* net.javacrumbs.json-unit:json-unit-assertj [2.28.0 -> 2.32.0]
* com.microsoft.azure:applicationinsights-agent [3.2.5 -> 3.2.7]
Also applied suppression for the ktlint reporter: CVE-2019-9658 and CVE-2019-10782
> Bump HMPPS Gradle plugin to v4.1.0

- build.gradle
See https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html
> Use Spring-managed dependency versions for Jackson, Oracle JDBC, and Lombok

- build.gradle
This suppress jackson vulnerability CVE-2020-36518 in trivyignore
> Bump HMPPS Gradle plugin to 4.1.1

- .circleci/config.yml
This fixes various API compatibility issues which prevented the workflow from queueing deployments
> Bump queue orb to 1.6.5

- .circleci/config.yml
This prevents branch deployment failures when creating lots of PRs (e.g. dependabot)
> Increase max queue time for deployments to 30 minutes

- catalog-info.yaml
Adds a Backstage entity metadata file to this repository so that the
component can be added to the developer portal
(https://developer-portal.apps.live.cloud-platform.service.justice.gov.uk/catalog)
Strategically, this file will replace most of https://github.com/ministryofjustice/hmpps-architecture-as-code/blob/main/src/main/kotlin/uk/gov/justice/hmpps/architecture/model/Delius.kt
Similar:
- https://github.com/ministryofjustice/hmpps-delius-api/pull/275
> Define community-api for developer portal

- src/main/resources/application.yml
Adds the new contract type NSI mappings for the new contracts going live 31st October.
> onboarding new contracts for FBD-Y

- helm_deploy/values-test.yaml
To avoid repeated exceptions while the Delius database is offline
> PI-2888 Shutdown Community API in test at 9pm
